image: registry.todevski.com/docker/images/golang-builder

services:
  - docker:dind

stages:
  - test
  - deploy

before_script:
  - mkdir -p go
  - export GOPATH=$CI_PROJECT_DIR/go
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cd "$(gopathify $CI_PROJECT_URL)"

test:
  stage: test
  script:
    - make test

container:
  stage: deploy
  script:
    - operator-sdk build $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE
  except:
    - tags

container-tag:
  stage: deploy
  script:
    - operator-sdk build $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE
  only:
    - tag