apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmcharts.helm.kubedex.com
spec:
  group: helm.kubedex.com
  names:
    kind: HelmChart
    listKind: HelmChartList
    plural: helmcharts
    singular: helmchart
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
