apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helm-controller
  template:
    metadata:
      labels:
        name: helm-controller
    spec:
      serviceAccountName: helm-controller
      containers:
        - name: helm-controller
          image: kubedex/helm-controller:v1.0.1
          command:
          - helm-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "helm-controller"
            - name: JOB_IMAGE
              value: "kubedex/helm-controller:v1.0.0"
            - name: API_GROUP
              value: "helm.abc.com"
            - name: API_VERSION
              value: "v1"
