// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/pearsontechnology/helm-controller/pkg/apis/helm/v1.HelmChart":       schema_pkg_apis_helm_v1_HelmChart(ref),
		"github.com/pearsontechnology/helm-controller/pkg/apis/helm/v1.HelmChartSpec":   schema_pkg_apis_helm_v1_HelmChartSpec(ref),
		"github.com/pearsontechnology/helm-controller/pkg/apis/helm/v1.HelmChartStatus": schema_pkg_apis_helm_v1_HelmChartStatus(ref),
	}
}

func schema_pkg_apis_helm_v1_HelmChart(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HelmChart is the Schema for the helmcharts API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/pearsontechnology/helm-controller/pkg/apis/helm/v1.HelmChartSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/pearsontechnology/helm-controller/pkg/apis/helm/v1.HelmChartStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/pearsontechnology/helm-controller/pkg/apis/helm/v1.HelmChartSpec", "github.com/pearsontechnology/helm-controller/pkg/apis/helm/v1.HelmChartStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_helm_v1_HelmChartSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HelmChartSpec defines the desired state of HelmChart",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_helm_v1_HelmChartStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HelmChartStatus defines the observed state of HelmChart",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
